### ISSUE TITLE
How to use two Cameras to calibration checkerboard 

### ISSUE THREAD

**Issue by bin851007** [davidpagnon/pose2sim#1]
Hello , I am currently using Pose2Sim tools but i have some problems that Cameras calibration uses to 
 checkerboard , I will use two cameras to calibration with checkerboard , but i don't know how to use it . Can you give me tutorial video or more detail to me ? If you can help me I will so grateful for all your help.

**Comment by davidpagnon** [comment]
Hi,

Calibration is the most difficult part to define in the code, because there are so many ways to do it, and so many ways it could go wrong. Hence, it is hard to tell you what's wrong in your calibration. As a consequence, if you have the chance to use a marker-based calibration, it's much easier to just convert it. 

Can you tell me what your error is, so that I can see at what point it doesn't work?
Did you follow closely these steps, and make sure your folder hierarchy follows what's needed?
![image](https://user-images.githubusercontent.com/54667644/166246593-66d469b7-363c-4739-8922-2cfa110342fd.png)
![image](https://user-images.githubusercontent.com/54667644/166246404-b57cdbc5-28b8-4df2-aa5e-555f5960589d.png)

An other usual issue occurs when the checkerboard is too small as regards to the image size (or too far from the camera): corner detection then doesn't work well so the calibration is wrong. Also, I would advise you to read and test the OpenCV tutorial, as my calibration code is closely based on it: https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html

Moreover, only 2 cameras is the bare minimum for triangulation and you may not get good results. You'll have to make sure your person is correctly detected by OpenPose at all time by each camera. You will also need to change the  minimum number of cameras for triangulation in your Config.toml file.
To be fair, two cameras may be a little

**Comment by bin851007** [comment]
I have try to put the images to calib-2d, and use "Pose2Sim.calibrateCams()" , but it doesn't work, output the empty list.
![3](https://user-images.githubusercontent.com/104242314/168752810-2f5b4a95-83e5-4f90-b46c-0f99e2473531.JPG)
![4](https://user-images.githubusercontent.com/104242314/168752838-fe2fe14a-69d4-47eb-aec8-20510a877578.JPG)

**Comment by davidpagnon** [comment]
Dear Jack,

I realize I may need to make it clearer in the Readme: 
- calib_camN_img must be folders, not files.
- These folders must have a large number of checkerboard images inside.
- One of these images (the first or the last, typically) must have the checkerboard at the origin of your coordinate system. 
It doesn't really matter if your origin is not on the floor or if the coordinate system it slanted, but you need to make sure you place the checkerboard precisely in the same place. It's better if all cameras film at the same time so that you are sure there is no small rotation or translation in the reference image which would screw up your calibration.

Here, the code doesn't find any folder, so it believes there is no cameras and outputs a calibration file with no cameras.


Other options : 
- Use the calibration code of Anipose https://anipose.readthedocs.io/en/latest/tutorial.html#calibrating-the-cameras. I use the exact same folder structure and the same toml calibration file type so it should be seamless. 
- Use video cameras that can be calibrated with a wand equipped with markers (e.g. Qualisys Miqus cameras), and use calibrateCams() to convert to toml file.

**Comment by davidpagnon** [comment]
Copied issue to the new repository:
https://github.com/perfanalytics/pose2sim/issues/4
